# Generated by Django 5.2.5 on 2025-10-05 16:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_company_unique_company_type'),
        ('inventory', '0007_inventoryitem_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the production formula/recipe', max_length=255)),
                ('unit_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='How many units this formula produces (e.g., 1 cake, 5 gallons)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, help_text='Description of the production process')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Labor cost per unit produced', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overhead cost per unit produced (electricity, etc.)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_formulas', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_formulas', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(help_text='The finished product that will be created', on_delete=django.db.models.deletion.CASCADE, related_name='production_formulas', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of units to produce', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('planned_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actual_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_overhead_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.productionformula')),
            ],
            options={
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='inventory.inventoryitem')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='production.productionorder')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of this material needed per formula unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(help_text='Raw material or component used in production', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_formulas', to='inventory.inventoryitem')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='production.productionformula')),
            ],
            options={
                'ordering': ['material__name'],
                'unique_together': {('formula', 'material')},
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('usage_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_usages', to='inventory.inventorybatch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_usages', to='inventory.inventoryitem')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='production.productionorder')),
            ],
            options={
                'unique_together': {('production_order', 'material', 'batch')},
            },
        ),
    ]
