# Generated by Django 5.2.5 on 2025-10-08 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryitem_item_type'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaingredient',
            name='material',
            field=models.ForeignKey(help_text='Raw material or component used in production', limit_choices_to={'item_type': 'stock_item'}, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_formulas', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='productionformula',
            name='finished_product',
            field=models.ForeignKey(help_text='The finished product that will be created', limit_choices_to={'item_type': 'finished_good'}, on_delete=django.db.models.deletion.CASCADE, related_name='production_formulas', to='inventory.inventoryitem'),
        ),
    ]
