# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name or company name of the entity.', max_length=255)),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('both', 'Both')], default='customer', help_text='Designates whether this entity is a customer, vendor, or both.', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The maximum amount of credit to extend to this customer. 0 means no limit.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
                ('payable_account', models.OneToOneField(blank=True, help_text='The Accounts Payable ledger account for this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payable', to='accounts.account')),
                ('receivable_account', models.OneToOneField(blank=True, help_text='The Accounts Receivable ledger account for this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_receivable', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'email'), ('company', 'name'), ('company', 'phone')},
            },
        ),
    ]
