# Generated by Django 5.2.5 on 2025-09-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
    ]
