# Generated by Django 5.2.5 on 2025-09-09 14:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20250909_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payable_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding amount company owes to the vendor', max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='receivable_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding amount customer owes to the company', max_digits=15),
        ),
    ]
