# Generated by Django 5.2.5 on 2025-08-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='The unique number for this account (e.g., 1110, 4100).', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_control_account', models.BooleanField(default=False, help_text='True if this is a control account like Accounts Receivable or Accounts Payable.')),
                ('system_account', models.CharField(blank=True, choices=[('COGS', 'Cost of Goods Sold'), ('CASH', 'Default Cash/Bank'), ('INVENTORY', 'Inventory Asset'), ('AR', 'Accounts Receivable'), ('AP', 'Accounts Payable'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('SALES_TAX', 'Sales Tax Payable')], help_text='Designates this account for a special system purpose (e.g., COGS, Accounts Receivable).', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], default='ASSET', max_length=10)),
            ],
        ),
    ]
