# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='The parent account in the hierarchy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'account_number'), ('company', 'system_account')},
        ),
    ]
