# Generated by Django 5.2.5 on 2025-08-30 01:56

import apps.backup.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('company', models.OneToOneField(limit_choices_to={'company_type': 'USER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='backup_settings', serialize=False, to='core.company')),
                ('backup_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', help_text='How often to automatically perform data backups.', max_length=10)),
                ('audit_reminder_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', help_text='How often to send reminders to the auditor.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.backup.models.backup_file_path)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes on the backup, e.g., reason for failure.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='backup.backupsettings')),
            ],
            options={
                'verbose_name': 'Backup Recipient',
                'verbose_name_plural': 'Backup Recipients',
                'unique_together': {('settings', 'email')},
            },
        ),
    ]
