# Generated by Django 5.2.5 on 2025-08-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        ('core', '0002_emailconfiguration'),
        ('customers', '0001_initial'),
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupsettings',
            name='audit_reminder_frequency',
        ),
        migrations.RemoveField(
            model_name='backupsettings',
            name='backup_frequency',
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='audit_frequency_days',
            field=models.PositiveIntegerField(default=30, help_text='How often to send audit reminders (in days). E.g., 30=monthly, 90=quarterly'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='audit_reminder_day_of_month',
            field=models.PositiveIntegerField(default=1, help_text='Which day of the month to send reminders (1-28)'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='audit_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Enable audit reminders'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic backups'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_frequency_days',
            field=models.PositiveIntegerField(default=7, help_text='How often to backup (in days). E.g., 1=daily, 7=weekly, 30=monthly'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_time',
            field=models.TimeField(default='02:00:00', help_text='What time of day to run backups (24-hour format)'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='days_after_due_final',
            field=models.PositiveIntegerField(default=30, help_text='Days after due date to send final overdue reminder'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='days_after_due_first',
            field=models.PositiveIntegerField(default=1, help_text='Days after due date to send first overdue reminder'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='days_after_due_second',
            field=models.PositiveIntegerField(default=7, help_text='Days after due date to send second overdue reminder'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='days_before_due_date',
            field=models.PositiveIntegerField(default=3, help_text='Days before due date to send first reminder'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='debtor_reminders_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic debtor reminders'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='last_audit_reminder_date',
            field=models.DateTimeField(blank=True, help_text='When the last audit reminder was sent', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='last_backup_date',
            field=models.DateTimeField(blank=True, help_text='When the last backup was completed', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='last_debtor_reminder_check',
            field=models.DateTimeField(blank=True, help_text='When debtor reminders were last checked', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='reminder_check_frequency_days',
            field=models.PositiveIntegerField(default=1, help_text='How often to check for due reminders (1=daily, 7=weekly)'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='reminder_time',
            field=models.TimeField(default='09:00:00', help_text='What time of day to send reminders (24-hour format)'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='send_after_due_enabled',
            field=models.BooleanField(default=True, help_text='Send reminders after due date'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='send_before_due_enabled',
            field=models.BooleanField(default=True, help_text='Send reminders before due date'),
        ),
        migrations.CreateModel(
            name='DebtorReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('BEFORE_DUE', 'Before Due Date'), ('FIRST_OVERDUE', 'First Overdue'), ('SECOND_OVERDUE', 'Second Overdue'), ('FINAL_OVERDUE', 'Final Overdue')], max_length=20)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-sent_date'],
                'unique_together': {('transaction', 'reminder_type')},
            },
        ),
    ]
