# Generated by Django 5.2.5 on 2025-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_remove_backupsettings_audit_reminder_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='audit_date_range_enabled',
            field=models.BooleanField(default=False, help_text='Enable date range filtering for audit documents'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='audit_end_date',
            field=models.DateField(blank=True, help_text='End date for audit period (leave blank for current date)', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='audit_start_date',
            field=models.DateField(blank=True, help_text='Start date for audit period (e.g., 6 months ago)', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_date_range_enabled',
            field=models.BooleanField(default=False, help_text='Enable date range filtering for backups'),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_end_date',
            field=models.DateField(blank=True, help_text='End date for backup data (leave blank for current date)', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_start_date',
            field=models.DateField(blank=True, help_text='Start date for backup data (leave blank for all data)', null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='incremental_backup_enabled',
            field=models.BooleanField(default=False, help_text='Only backup data changed since last successful backup'),
        ),
    ]
