# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company_type', models.CharField(choices=[('USER', 'User Company'), ('AUDITOR', 'Auditor Company')], default='USER', max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (₦)'), ('USD', 'United States Dollar ($)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)')], default='NGN', max_length=3)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('is_licensed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company_type',), name='unique_company_type')],
            },
        ),
    ]
