# Generated by Django 5.2.5 on 2025-08-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Gmail address for sending backups', max_length=254)),
                ('app_password', models.CharField(blank=True, help_text='Gmail App Password (not your regular password)', max_length=100)),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='core.company')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
