# Generated by Django 5.2.5 on 2025-09-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company_type',
        ),
    ]
