# Generated by Django 5.2.5 on 2025-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_company_unique_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_closing_grace_period_months',
            field=models.PositiveIntegerField(default=3, help_text='The number of months after the fiscal year ends where accountants can still make entries.'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end',
            field=models.DateField(blank=True, editable=False, help_text='The calculated end date of your financial year.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_start',
            field=models.DateField(blank=True, help_text='The start date of your financial year. The end date will be set automatically to 12 months later.', null=True),
        ),
    ]
