# Generated by Django 5.2.5 on 2025-09-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('TRIAL', '30 Days Free Trial'), ('BASIC', 'Basic (1 User)'), ('STANDARD', 'Standard (Up to 3 Users)'), ('DELUXE', 'Deluxe (Up to 5 Users)'), ('PREMIUM', 'Premium (Unlimited Users)')], max_length=20)),
                ('payment_receipt', models.FileField(help_text='Upload the proof of payment.', upload_to='payment_receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes for the superuser regarding this request.')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('TRIAL', '30 Days Free Trial'), ('BASIC', 'Basic (1 User)'), ('STANDARD', 'Standard (Up to 3 Users)'), ('DELUXE', 'Deluxe (Up to 5 Users)'), ('PREMIUM', 'Premium (Unlimited Users)')], default='TRIAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('activated_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Superuser can manually activate or deactivate a subscription.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company')),
            ],
        ),
    ]
