# Generated by Django 5.2.5 on 2025-09-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional: Any additional information or notes for our team.'),
        ),
    ]
