# Generated by Django 5.2.5 on 2025-09-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_registrationrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='years_paid',
            field=models.PositiveSmallIntegerField(default=1, help_text='Set the number of years the client has paid for.'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Upload the proof of payment (Required for paid plans).', null=True, upload_to='payment_receipts/%Y/%m/'),
        ),
    ]
