# Generated by Django 5.2.5 on 2025-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_registrationrequest_years_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='business_base_country',
            field=models.CharField(blank=True, default='', help_text='The primary country where your business operates.', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='business_industry',
            field=models.CharField(blank=True, choices=[('RETAIL', 'Retail / E-commerce'), ('SERVICES', 'Services (Consulting, Agency, etc.)'), ('MANUFACTURING', 'Manufacturing'), ('HOSPITALITY', 'Hospitality (Hotel, Restaurant)'), ('HEALTHCARE', 'Healthcare'), ('CONSTRUCTION', 'Construction / Real Estate'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
