# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to='core.company')),
                ('expense_account', models.ForeignKey(help_text='Required. The default expense account to use for transactions in this category.', limit_choices_to={'account_type__name__in': ['Expense', 'Cost of Goods Sold']}, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_categories', to='accounts.account')),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale / Invoice'), ('PURCHASE', 'Purchase / Bill'), ('EXPENSE', 'Expense')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Internal notes or memo.')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transaction_attachments/')),
                ('reference_number', models.CharField(blank=True, help_text='e.g., Invoice #, Bill #, Receipt #', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer or vendor for this transaction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
                ('journal_entry', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='journal.journalentry')),
                ('category', models.ForeignKey(blank=True, help_text='Categorize this transaction for reporting (e.g., Fuel, Utilities).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.transactioncategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Overrides the default item description if needed.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit.', max_digits=12)),
                ('item', models.ForeignKey(help_text='The product or service being sold/purchased.', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='inventory.inventoryitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction')),
            ],
        ),
    ]
