# Generated by Django 5.2.5 on 2025-08-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_emailconfiguration'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='expense_account',
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'Income/Revenue'), ('EXPENSE', 'Expense'), ('ASSET', 'Asset Purchase'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('TRANSFER', 'Transfer')], default='EXPENSE', max_length=20),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Default account to use for transactions in this category', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
