# Generated by Django 5.2.5 on 2025-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactioncategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale / Invoice'), ('PURCHASE', 'Purchase / Bill'), ('EXPENSE', 'Expense'), ('Payment Receipt', 'Payment Receipt')], max_length=50),
        ),
    ]
