# Generated by Django 5.2.5 on 2025-09-07 14:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ['account_type__category', 'name']},
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='category_type',
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='account_type',
            field=models.ForeignKey(default=1, help_text='Select the account type this category belongs to', on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='allowed_transaction_types',
            field=models.JSONField(default=list, help_text='Transaction types that can use this category'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 7, 14, 48, 32, 181610, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale / Invoice'), ('PURCHASE', 'Purchase / Bill'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment Receipt'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment Entry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Default account for this category (must belong to selected account type)', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
    ]
