# Generated by Django 5.2.5 on 2025-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactioncategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale / Invoice'), ('PURCHASE', 'Purchase / Bill'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment Received'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment Entry')], max_length=50),
        ),
    ]
