# Generated by Django 5.2.5 on 2025-10-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('transactions', '0006_transaction_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(help_text='The expense or asset account to debit.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_lines', to='accounts.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='transactions.transaction')),
            ],
        ),
    ]
