# Generated by Django 5.2.5 on 2025-08-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Nos', 'Nos (Numbers)'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('m', 'Meter'), ('sqm', 'Square Meter'), ('m3', 'Cubic Meter'), ('ton', 'Tonne'), ('bag', 'Bag'), ('box', 'Box'), ('roll', 'Roll'), ('set', 'Set'), ('per_hour', 'Per hour'), ('per_day', 'Per Day'), ('charges', 'Charges')], default='Nos', max_length=10),
        ),
    ]
