# Generated by Django 5.2.5 on 2025-09-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_unit_of_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='costing_method',
            field=models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WEIGHTED_AVG', 'Weighted Average'), ('SPECIFIC_ID', 'Specific Identification')], default='WEIGHTED_AVG', help_text='Method used to calculate cost of goods sold', max_length=15),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='cost_layers_used',
            field=models.JSONField(blank=True, default=list, help_text='Cost layers consumed for sales transactions'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this transaction', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this transaction', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Original quantity purchased at this cost', max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, help_text='Quantity remaining at this cost layer', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit for this layer', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Purchase order or transaction reference', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['purchase_date', 'id'],
            },
        ),
    ]
