# Generated by Django 5.2.5 on 2025-09-08 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_allow_fractional_quantities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='costing_method',
            field=models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('WEIGHTED_AVG', 'Weighted Average'), ('SPECIFIC_ID', 'Specific Identification (Batch Tracking)'), ('PRICE_ADJ', 'Price Adjustment Method')], default='WEIGHTED_AVG', help_text="Method used to calculate cost of goods sold. Use 'Specific Identification' for batch tracking.", max_length=15),
        ),
        migrations.CreateModel(
            name='InventoryPriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_unit_cost', models.DecimalField(decimal_places=2, help_text='Previous unit cost before adjustment', max_digits=12)),
                ('new_unit_cost', models.DecimalField(decimal_places=2, help_text='New unit cost after adjustment', max_digits=12)),
                ('quantity_affected', models.DecimalField(decimal_places=2, help_text='Quantity of inventory affected by this adjustment', max_digits=12)),
                ('adjustment_reason', models.CharField(help_text='Reason for the price adjustment', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Reference document or approval number', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Price Adjustment',
                'verbose_name_plural': 'Price Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
