# Generated by Django 5.2.5 on 2025-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_costing_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='fair_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fair market value per unit for gifts/donations or custom valuations', max_digits=12, null=True),
        ),
    ]
