# Generated by Django 5.2.5 on 2025-09-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorymovement_fair_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this item is active and available for selection'),
        ),
    ]
