# Generated by Django 5.2.5 on 2025-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('Products', [('stock_item', 'Stock Item'), ('finished_good', 'Finished Good')]), ('service', 'Service')], default='stock_item', max_length=20),
        ),
    ]
