# Generated by Django 5.2 on 2025-10-09 01:00

from django.db import migrations

def migrate_item_types(apps, schema_editor):
    """
    Find all InventoryItem instances with the old 'product' type
    and update them to the new 'stock_item' type.
    """
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    # Update all items where item_type is 'product' to 'stock_item'
    InventoryItem.objects.filter(item_type='product').update(item_type='stock_item')

def reverse_migration(apps, schema_editor):
    """
    (Optional) Defines how to reverse the migration if needed.
    """
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryItem.objects.filter(item_type='stock_item').update(item_type='product')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventoryitem_item_type'), # Make sure this matches your previous migration file name
    ]

    operations = [
        migrations.RunPython(migrate_item_types, reverse_code=reverse_migration),
    ]

