# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('REPAIR', 'Repair'), ('ROUTINE', 'Routine Service'), ('UPGRADE', 'Upgrade')], max_length=10)),
                ('description', models.TextField(help_text='Describe the work that was done.')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for which depreciation was calculated (e.g., end of the month).')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of depreciation posted for this period.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Depreciation Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_method', models.CharField(choices=[('SL', 'Straight-Line'), ('DB', 'Declining Balance')], default='SL', max_length=2)),
                ('useful_life_years', models.PositiveIntegerField(help_text='The number of years the asset is expected to be in service.')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The estimated residual value of an asset at the end of its useful life.', max_digits=12)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='The contra-asset account to credit for accumulated depreciation.', on_delete=django.db.models.deletion.PROTECT, related_name='asset_accumulated_depreciation', to='accounts.account')),
                ('asset_account', models.ForeignKey(help_text="The primary asset account (e.g., 'Vehicles', 'Machinery').", on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounts.account')),
            ],
        ),
    ]
