# Generated by Django 5.2.5 on 2025-08-30 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_expense_account',
            field=models.ForeignKey(help_text='The account to debit for depreciation expense.', on_delete=django.db.models.deletion.PROTECT, related_name='asset_depreciation_expenses', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='journal_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_record', to='journal.journalentry'),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationentry',
            unique_together={('asset', 'date')},
        ),
    ]
