# Generated by Django 5.2.5 on 2025-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('SL', 'Straight-Line'), ('DB', 'Declining Balance')], default='SL', help_text='Method used to calculate annual depreciation', max_length=2),
        ),
    ]
