# Generated by Django 5.2.5 on 2025-09-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_depreciation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='estimated_total_units',
            field=models.PositiveIntegerField(blank=True, help_text='Total estimated units of production (for Units of Production method)', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='units_produced_to_date',
            field=models.PositiveIntegerField(default=0, help_text='Total units produced to date'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='units_produced',
            field=models.PositiveIntegerField(default=0, help_text='Units produced this period (for UOP method)'),
        ),
        migrations.AddField(
            model_name='depreciationentry',
            name='year_number',
            field=models.PositiveIntegerField(default=1, help_text="Which year of the asset's life"),
        ),
        migrations.AlterField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('SL', 'Straight-Line'), ('DB', 'Declining Balance'), ('DD', 'Double Declining Balance'), ('DB150', '150% Declining Balance'), ('SYD', 'Sum of Years Digits'), ('UOP', 'Units of Production'), ('MACRS', 'MACRS (US Tax)'), ('NONE', 'No Depreciation')], default='SL', help_text='Method used to calculate annual depreciation', max_length=10),
        ),
    ]
